<a href="https://colab.research.google.com/github/juhee3199/kakaotalk_analysis_proj/blob/main/warming_up/kakao_proj_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# konlpy Mecab 설치
!set -x \
&& pip install konlpy \
&& curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh | bash -x

from konlpy.tag import Mecab


+ pip install konlpy
     |████████████████████████████████| 19.4MB 5.6MB/s 
     |████████████████████████████████| 460kB 36.4MB/s 
     |████████████████████████████████| 92kB 7.3MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
+ curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh
+ bash -x
+ mecab_dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic
+ set -e
++ uname
+ os=Linux
+ [[ ! Linux == \L\i\n\u\x ]]
+ hash sudo
+ sudo=sudo
+ python=python3
+ hash pyenv
+ at_user_site=
++ check_python_site_location_is_writable
++ python3 -
+ [[ 1 == \0 ]]
+ hash automake
+ echo 'Installing automake (A dependency for mecab-ko)'
Installing automake (A dependency for mecab-ko)
+ install_automake
+ '[' Linux == Linux ']'
++ grep -Ei 'debian|buntu|mint' /etc/lsb-release /etc/os-release
+ '[' '/etc/lsb-release:DISTRIB_ID=Ubuntu
/etc/lsb-release:DISTRIB_DESCRIPTION="Ubuntu 18.04.5 

In [ ]:
import pandas as pd
import numpy as np
import re


# Pandas 처리

In [ ]:
def dateformat(y=0,m=0,d=0,h=0,mm=0,s=0):
    return "%d-%02d-%02d %02d:%02d:%02d"%(y,m,d,h,mm,s)

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 72 not upgraded.
Need to get 9,604 kB of archives.
After this operation, 29.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 fonts-nanum all 20170925-1 [9,604 kB]
Fetched 9,604 kB in 1s (9,543 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletyp

In [ ]:
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic') 

In [ ]:
# txt인 경우 (iphone)

#f = open('Talk_2021.5.3 23:58-1.txt', mode='r', encoding='utf-8')
f = open('Talk_2021.5.13 19_07-1.txt', mode='r', encoding='utf-8')

#f = open('Talk_2021.5.19 23_24-1.txt', mode='r', encoding='utf-8')

file_name = f.readline()
save_date_re = re.compile('저장한 날짜 : ([0-9]{4})\. ([0-9]{1,2})\. ([0-9]{1,2})\. (오전|오후) ([0-9]{1,2}):([0-9]{2})')
m = save_date_re.match(f.readline())
if m[4]=='오후':
  save_date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5])+12, int(m[6]))

else: 
  save_date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5]), int(m[6]))

f.readline() # 공백 제거
f.readline() # 공백 제거
f.readline() # 공백 제거

history = []
histline = ''
date = None

date_re = re.compile('([0-9]{4})년 ([0-9]{1,2})월 ([0-9]{1,2})일 ((월|화|수|목|금|토|일)요일)')
invite_re = re.compile('([0-9]{4})\. ([0-9]{1,2})\. ([0-9]{1,2})\. (오전|오후) ([0-9]{1,2}):([0-9]{2}): ((.+)님이 .+ 초대했습니다.)') 
exit_re = re.compile('([0-9]{4})\. ([0-9]{1,2})\. ([0-9]{1,2})\. (오전|오후) ([0-9]{1,2}):([0-9]{2}): ((.+)님이 나갔습니다.)')
chat_re = re.compile('([0-9]{4})\. ([0-9]{1,2})\. ([0-9]{1,2})\. (오전|오후) ([0-9]{1,2}):([0-9]{2}), (.+) : (.+)')

chat_temp = ''

i=0
while True:
    line = f.readline()
    if not line: 
        break
    # print(line, end='')

    # chat
    m = chat_re.match(line)
    if m:
        if m[4]=='오후':
          date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5])+12, int(m[6]))
        else: 
          date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5]), int(m[6]))
        user = m[7]
        content = m[8]
        history.append([date, user, content])
        continue
    # date
    m = date_re.match(line)
    if m:
        date = dateformat(int(m[1]), int(m[2]), int(m[3]))
        continue
    # invite
    m = invite_re.match(line)
    if m:
        #date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5]), int(m[6]))
        if m[4]=='오후':
          date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5])+12, int(m[6]))
        else: 
          date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5]), int(m[6]))
        user = m[8]
        content = m[7]
        history.append([date, user, content])
        continue
    # exit
    m = exit_re.match(line)
    if m:
        #date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5]), int(m[6]))
        if m[4]=='오후':
          date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5])+12, int(m[6]))
        else: 
          date = dateformat(int(m[1]), int(m[2]), int(m[3]), int(m[5]), int(m[6]))
        user = m[7]
        content = m[8]
        history.append([date, user, content])
        continue
    # \n chat
    history[-1][2] += line
df = pd.DataFrame(history, columns=['Date', 'User', 'Message'])

In [ ]:
df

Date  ...                                            Message
0     2020-08-01 21:13:00  ...                    이장후님이 최우혁님, 나영채님과 이주희님을 초대했습니다.
1     2020-08-01 21:13:00  ...                                             안녕하세요!
2     2020-08-01 21:13:00  ...                                              이모티콘 
3     2020-08-01 21:16:00  ...  - SAI 캘린더 연동하기- SAI 회의록 notion 초대\n- SAI 회의록 구...
4     2020-08-01 21:21:00  ...                        Notion google mail 로 초대했습니담
...                   ...  ...                                                ...
4973  2021-05-13 18:06:00  ...                                데이터로 바꾸는 코드를 올려놓은건데
4974  2021-05-13 18:06:00  ...                                           아아ㅏ 글쿵..
4975  2021-05-13 18:07:00  ...                         그럼 각자 데이터 변환해서 실습해봐야하는거지??
4976  2021-05-13 18:50:00  ...                                                  녜
4977  2021-05-13 19:07:00  ...                                                  옙

[4978 rows x 3 columns]

In [ ]:
import pandas as pd
#df2.to_csv('kakaotalk_2021_staff_4.csv')


NameError: ignored

# analysis

In [ ]:
import pandas as pd

df = pd.read_csv('kakaotalk_2021_staff_4.csv', usecols=range(1,4))
df

Date  ...                                            Message
0     2020-08-01 21:13:00  ...  이장후님이 최우혁님, 나영채님과 이주희님을 초대했습니다.2020. 8. 1. 오후 ...
1     2020-08-01 23:37:00  ...                                                 사진
2     2020-08-01 23:38:00  ...         저희 일정 관련해서 우선 괜찮나 실험해볼 수 있는 캘린더를 공유설정했습니다.
3     2020-08-01 23:38:00  ...                구글 컴퓨터에서 아마 메일 받으면 캘린더 구독할 수 있을거에요.
4     2020-08-01 23:38:00  ...                            ㅋㅋㅋ 별로 받고싶지 않은 일정이긴 할텐데
...                   ...  ...                                                ...
1751  2021-05-11 10:22:00  ...                                                아닌가
1752  2021-05-11 10:23:00  ...                                  저게아마 figure 1 이지?
1753  2021-05-11 10:24:00  ...                                    Fig 1 어쩌고 하기전까지
1754  2021-05-11 10:24:00  ...                                    그냥없는그림이라고 생각해도돼
1755  2021-05-11 10:26:00  ...  아 그냥 내가 번역을 좀 잘못생각한듯 ㅋㅋ ㅈㅅ ;;\n2021. 5. 13. 오후...

[1756 rows x 3 columns]

In [ ]:
"""#print(df['Message'].values)#.split()

df['M_split'] =0

j=0
for i in df['Message'].values:
  df['M_split'][j] = i.split()
  j+=1

df['M_split']"""

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


0       [이장후님이, 최우혁님,, 나영채님과, 이주희님을, 초대했습니다.2020., 8.,...
1                                                    [사진]
2       [저희, 일정, 관련해서, 우선, 괜찮나, 실험해볼, 수, 있는, 캘린더를, 공유설...
3           [구글, 컴퓨터에서, 아마, 메일, 받으면, 캘린더, 구독할, 수, 있을거에요.]
4                          [ㅋㅋㅋ, 별로, 받고싶지, 않은, 일정이긴, 할텐데]
                              ...                        
1751                                                [아닌가]
1752                               [저게아마, figure, 1, 이지?]
1753                                 [Fig, 1, 어쩌고, 하기전까지]
1754                                   [그냥없는그림이라고, 생각해도돼]
1755    [아, 그냥, 내가, 번역을, 좀, 잘못생각한듯, ㅋㅋ, ㅈㅅ, ;;, 2021.,...
Name: M_split, Length: 1756, dtype: object

### khaiii 카카오 형태소 분석기 사용

In [ ]:
!git clone https://github.com/kakao/khaiii.git

!pip install cmake

!mkdir build

!cd build && cmake /content/khaiii
!cd /content/build/ && make all
!cd /content/build/ && make resource
!cd /content/build && make install
!cd /content/build && make package_python
!pip install /content/build/package_python

Cloning into 'khaiii'...
remote: Enumerating objects: 1009, done.
remote: Counting objects: 100% (132/132), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 1009 (delta 41), reused 69 (delta 24), pack-reused 877
Receiving objects: 100% (1009/1009), 33.06 MiB | 27.86 MiB/s, done.
Resolving deltas: 100% (399/399), done.
-- [hunter] Initializing Hunter workspace (70287b1ffa810ee4e952052a9adff9b4856d0d54)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz
-- [hunter]   -> /root/.hunter/_Base/Download/Hunter/0.23.34/70287b1
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -

In [ ]:
 # 필요한 형태 및 단어로 변형해서 반환
 
 def return_need_word(morph):

   # 조사, 어미, 접미사, 접두사, 특수기호, 숫자 제거
   # 체언 접두사와 어근은 제거하지 않음
  not_use = ['JKS','JKC','JKG','JKO','JKB','JKV','JKQ','JX','JC',
          'EP','EF','EC','ETN','ETM','XSN','XSV','XSA',
          'SF','SP','SS','SE','SO','SW','SWK','SN']

  stopwords = ['에','을','를','이', '은','는','도','다','라' '있', '하', '것', '들', '그', '되', '수', '이', '보', '않', '없', '나', '주', '아니', '등', '같', '때', '년', 
              '가', '한', '지', '대하', '오', '말', '일', '그렇', '위하']      

  if (morph.tag in not_use) or (morph.lex in stopwords):
      return '' 
  # 동사에 '다'
  elif morph.tag == 'VA' or morph.tag == 'VV':
      return morph.lex + '다'
  else:
      word = morph.lex
      word = re.sub('[\n+]', '', word)
      word = re.sub("https.*", '', word)
      return word

In [ ]:
# 형태소 분석 및 전처리

from khaiii import KhaiiiApi

def khaiii_text_preprocessing(text_list):
    tokenizer = KhaiiiApi() #형태소 분석기

    token_list = [] 
    
    for text in text_list:
        morph_list = []
        for word in tokenizer.analyze(text):  # 형태소 분석
            for morph in word.morphs:
              morph_lex = return_need_word(morph) #
              if morph_lex != '':
                morph_list.append(morph_lex)
          
        token_list.append(morph_list)
        
    return token_list, tokenizer

df['khaiii'], khaiii = khaiii_text_preprocessing(df['Message'])
df['khaiii']

0       [장후, 최, 우혁, 영채, 이주, 희, 초대, 오후, 이장후, 안녕, 오후, 나영...
1                                                    [사진]
2              [저희, 일정, 관련, 우선, 괜찮다, 실험, 있다, 캘린더, 공유, 설정]
3                   [구글, 컴퓨터, 아마, 메일, 받다, 캘린더, 구독, 있다, 거]
4                               [ㅋㅋ, ㅋ, 별로, 받다, 싶, 일정, 터]
                              ...                        
1751                                                   []
1752                                  [저, 게아, 마다, figure]
1753                                        [Fig, 어쩌다, 전]
1754                                         [그냥, 그림, 생각]
1755    [아, 그냥, 내, 번역, 좀, 잘못, 생각, 듯, ㅋㅋ, ㅈㅅ, 오후, 이주희, ...
Name: khaiii, Length: 1756, dtype: object

##### 많이 사용하는 단어

In [ ]:
from khaiii import KhaiiiApi

def khaiii_text_preprocessing(text_list):
    tokenizer = KhaiiiApi() #형태소 분석기
  
    token_list = [] 
    
    for text in text_list:
        morph_list = []
        for word in tokenizer.analyze(text):  # 형태소 분석
            
            for morph in word.morphs:
              morph_lex = return_need_word(morph) #
              if morph_lex != '':
                morph_list.append(morph_lex)
          
        token_list.append(morph_list)
        

        # bow
        word2index={}  
        bow=[]  
        for voca in morph_lex:  
                #if voca in stopwords:
                #  continue
                #elif voca not in word2index.keys():  
                if voca not in word2index.keys():  
                    word2index[voca]=len(word2index)  
        # token을 읽으면서, word2index에 없는 (not in) 단어는 새로 추가하고, 이미 있는 단어는 넘깁니다.   
                    bow.insert(len(word2index)-1,1)
        # BoW 전체에 전부 기본값 1을 넣어줍니다. 단어의 개수는 최소 1개 이상이기 때문입니다.  
                else:
                    index=word2index.get(voca)
        # 재등장하는 단어의 인덱스를 받아옵니다.
                    bow[index]=bow[index]+1
        # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더해줍니다. (단어의 개수를 세는 것입니다.)  
        #print(word2index)

        #word_name = word2index

        word_name.append(list(word2index.keys()))
        word_cnt.append(bow)
#        word_cnt.append(list(word2index.values()))  
        
    return token_list, tokenizer, word_name, word_cnt

df['khaiii_content'], khaiii, khaiii_word_name, khaiii_word_cnt = khaiii_text_preprocessing(df['Message'])

In [ ]:
khaiii_word_name

['이장',
 '후',
 '님',
 '최우혁',
 '나영',
 '채',
 '과',
 '이주희',
 '초대',
 '했습니다',
 '오후',
 '안녕하세요',
 '이모티콘',
 'SAI',
 '캘린더',
 '연동',
 '하기',
 '회의',
 '록',
 'notion',
 '구글독스',
 '내용',
 '으로',
 '옮기기',
 'Notion',
 'google',
 'mail',
 '로',
 '했',
 '습',
 '니',
 '담',
 '저',
 '와',
 '영채',
 '다음주',
 '화요일',
 '할',
 '간단히',
 '정리',
 '해',
 '둘',
 '생각',
 '이지만',
 '통해',
 '역할',
 '분담',
 '해서',
 '작성',
 '거나',
 '해보아야',
 '만',
 '있다면',
 '직접',
 '들어가서',
 '업로드',
 '주시',
 '면',
 '됩니다',
 '뭐',
 '저희',
 '동아리',
 '뿐',
 '아니라',
 '나중',
 '에도',
 '많이',
 '사용',
 '하실',
 '테',
 '니까',
 '하는거',
 '이참',
 '익혀',
 '두세요',
 '넵',
 '네',
 '사진',
 '저희',
 '일정',
 '관련',
 '해서',
 '우선',
 '괜찮나',
 '실험',
 '해볼',
 '있는',
 '캘린더',
 '공유',
 '설정',
 '했습니다',
 '구글',
 '컴퓨터',
 '에서',
 '아마',
 '메일',
 '받으면',
 '캘린더',
 '구독',
 '할',
 '있을거에요',
 'ㅋㅋㅋ',
 '별로',
 '받고싶지',
 '않은',
 '일정',
 '이긴',
 '할텐데',
 '받아',
 '봐줘요',
 '네넹',
 '확인',
 '했어요',
 '오후',
 '이주희',
 '저희',
 '화요일',
 '시',
 '온라인',
 '으로',
 '회의',
 '하는거',
 '맞나요',
 '제',
 '일이',
 '있어서',
 '혹시',
 '시간',
 '일찍',
 '할',
 '있을까요',
 '최우혁',
 '전',
 '좋아요',
 '나영',
 '채',
 '네네',


In [ ]:
khaiii_word_name = np.concatenate(khaiii_word_name).tolist()
khaiii_word_name

khaiii_word_cnt = np.concatenate(khaiii_word_cnt).tolist()
# word_cnt

khaiii_word_df = pd.DataFrame({
            'khaiii_word_name': khaiii_word_name,
           'khaiii_word_cnt': khaiii_word_cnt})
khaiii_word_df

ValueError: ignored

In [ ]:
khaiii_word_name

In [ ]:
# 형태소 분석 및 전처리

from khaiii import KhaiiiApi

def khaiii_text_preprocessing(text_list):
    tokenizer = KhaiiiApi() #형태소 분석기

    token_list = [] 
    
    for text in text_list:
       
        morph_list = []
        for word in tokenizer.analyze(text):  # 형태소 분석
            for morph in word.morphs:
              #morph_lex = return_need_word(morph) #
              #if morph_lex != '':
                morph_list.append((morph.lex, morph.tag))
          
        token_list.append(morph_list)
        
    return token_list, tokenizer

df['khaiii_22'], khaiii = khaiii_text_preprocessing(df['Message'])
df['khaiii_22']

0       [(이, NNP), (장후, NNG), (님, XSN), (이, JKS), (최, ...
1                                             [(사진, NNG)]
2       [(저희, NP), (일정, NNG), (관련, NNG), (하, XSV), (여서...
3       [(구글, MAG), (컴퓨터, NNG), (에서, JKB), (아마, MAG), ...
4       [(ㅋㅋ, IC), (ㅋ, NNG), (별로, MAG), (받, VV), (고, E...
                              ...                        
1751                                [(아니, VCN), (ㄴ가, EC)]
1752    [(저, NP), (게아, NNG), (마, VA), (figure, SL), (1...
1753    [(Fig, SL), (1, SN), (어쩌, VV), (고, EC), (하, VV...
1754    [(그냥, MAG), (없, VA), (는, ETM), (그림, NNG), (이, ...
1755    [(아, IC), (그냥, MAG), (내, NP), (가, JKS), (번역, N...
Name: khaiii_22, Length: 1756, dtype: object

In [ ]:
df['khaiii'][1755]

['아',
 '그냥',
 '내',
 '번역',
 '좀',
 '잘못',
 '생각',
 '듯',
 'ㅋㅋ',
 'ㅈㅅ',
 '오후',
 '이주희',
 '영채',
 '카톡로그분석',
 '너',
 '쓰다',
 '데이터',
 '올리다',
 '두',
 '하다',
 '않',
 '오후',
 '나영채',
 '녜',
 '아뇨',
 '그',
 '오후',
 '나영',
 '채',
 '데이터',
 '바꾸다',
 '코드',
 '올려놓다',
 '오후',
 '이주희',
 '아아',
 'ㅏ',
 '글',
 '쿵',
 '오후',
 '이주희',
 '그럼',
 '각자',
 '데이터',
 '변환',
 '실습',
 '보',
 '하',
 '거',
 '이',
 '오후',
 '나영채',
 '녜',
 '오후',
 '이주희',
 '옙']

In [ ]:
  word_name[1755]

['아',
 '그냥',
 '내',
 '가',
 '번역',
 '을',
 '좀',
 '잘못',
 '생각',
 '한',
 '듯',
 'ㅋㅋ',
 'ㅈㅅ',
 '오후',
 '이주희',
 '영채',
 '야',
 '카톡',
 '로그',
 '분석',
 '너',
 '썼던',
 '데이터',
 '올려',
 '뒀다고',
 '하지',
 '않았어',
 '나영',
 '채',
 '녜',
 '아뇨',
 '그',
 '로',
 '바꾸는',
 '코드',
 '를',
 '올려놓은',
 '건데',
 '아아',
 'ㅏ',
 '글쿵',
 '그럼',
 '각자',
 '변환',
 '해서',
 '실습',
 '해봐',
 '야하는거지',
 '옙']

In [ ]:
df['khaiii_22'][1755]

[('아', 'IC'),
 ('그냥', 'MAG'),
 ('내', 'NP'),
 ('가', 'JKS'),
 ('번역', 'NNG'),
 ('을', 'JKO'),
 ('좀', 'MAG'),
 ('잘못', 'MAG'),
 ('생각', 'NNG'),
 ('하', 'XSA'),
 ('ㄴ', 'ETM'),
 ('듯', 'NNB'),
 ('ㅋㅋ', 'NNG'),
 ('ㅈㅅ', 'NNG'),
 (';;', 'SP'),
 ('2021', 'SN'),
 ('.', 'SF'),
 ('5', 'SN'),
 ('.', 'SF'),
 ('13', 'SN'),
 ('.', 'SF'),
 ('오후', 'NNG'),
 ('5', 'SN'),
 (':', 'SP'),
 ('37', 'SN'),
 (',', 'SP'),
 ('이주희', 'NNP'),
 (':', 'SP'),
 ('영채', 'NNP'),
 ('야', 'JKV'),
 ('카톡로그분석', 'NNG'),
 ('너', 'NP'),
 ('가', 'JKS'),
 ('쓰', 'VV'),
 ('었', 'EP'),
 ('던', 'ETM'),
 ('데이터', 'NNG'),
 ('올리', 'VV'),
 ('어', 'EC'),
 ('두', 'VX'),
 ('었', 'EP'),
 ('다고', 'EC'),
 ('하', 'VV'),
 ('지', 'EC'),
 ('않', 'VX'),
 ('았', 'EP'),
 ('어', 'EF'),
 ('??', 'SF'),
 ('?', 'SF'),
 ('2021', 'SN'),
 ('.', 'SF'),
 ('5', 'SN'),
 ('.', 'SF'),
 ('13', 'SN'),
 ('.', 'SF'),
 ('오후', 'NNG'),
 ('6', 'SN'),
 (':', 'SP'),
 ('06', 'SN'),
 (',', 'SP'),
 ('나영채', 'NNP'),
 (':', 'SP'),
 ('녜', 'IC'),
 ('아뇨', 'IC'),
 ('그', 'MM'),
 ('2021', 'SN'),
 ('.', 'SF'),
 (

In [ ]:
for i in word_name[1755]:
    if i not in df['khaiii'][1755]:
      print(i)

가
을
한
야
카톡
로그
분석
썼던
올려
뒀다고
하지
않았어
로
바꾸는
를
올려놓은
건데
글쿵
해서
해봐
야하는거지


- 아래 okt와 비교

In [ ]:
df['khaiii'][3]

['구글',
 '컴퓨터',
 '에서',
 '아마',
 '메일',
 '받',
 '으면',
 '캘린더',
 '구독',
 '하',
 'ㄹ',
 '수',
 '있',
 '을',
 '거',
 '에요',
 '.']

In [ ]:
 word_name[3]

['구글', '컴퓨터', '에서', '아마', '메일', '받으면', '캘린더', '구독', '할', '수', '있을거에요']

In [ ]:
for i in word_name[3]:
    if i not in df['khaiii'][4]:
      print(i)

구글
컴퓨터
에서
아마
메일
받으면
캘린더
구독
할
수
있을거에요


In [ ]:
'이장' in word_name[0]

True

#### Mecab

In [ ]:
# 형태소 분석 및 전처리
def Mecab_text_preprocessing(text_list):
    tokenizer = Mecab() #형태소 분석기

    token_list = [] 
    
    for text in text_list:
        token = tokenizer.morphs(text) #형태소 분석

        token = [t for t in token] 
        token_list.append(token)
        
    return token_list, tokenizer

df['content'], mecab = Mecab_text_preprocessing(df['Message'])

In [ ]:
df['content']

0       [이, 장후, 님, 이, 최우혁, 님, ,, 나영채, 님, 과, 이주희, 님, 을,...
1                                                    [사진]
2       [저희, 일정, 관련, 해서, 우선, 괜찮, 나, 실험, 해, 볼, 수, 있, 는,...
3       [구글, 컴퓨터, 에서, 아마, 메일, 받, 으면, 캘린더, 구독, 할, 수, 있,...
4              [ㅋㅋㅋ, 별로, 받, 고, 싶, 지, 않, 은, 일정, 이, 긴, 할텐데]
                              ...                        
1751                                                [아닌가]
1752                         [저게, 아마, figure, 1, 이, 지, ?]
1753                         [Fig, 1, 어쩌, 고, 하, 기, 전, 까지]
1754                     [그냥, 없, 는, 그림, 이, 라고, 생각, 해도, 돼]
1755    [아, 그냥, 내, 가, 번역, 을, 좀, 잘못, 생각, 한, 듯, ㅋㅋ, ㅈ, ㅅ...
Name: content, Length: 1756, dtype: object

### okt(twitter) 사용

--> okt가 조금 더 나은것 같아서 사용함

In [ ]:
user_name = df.User.unique()[:4]
user_name

array(['이장후', '나영채', '최우혁', '이주희'], dtype=object)

In [ ]:
from konlpy.tag import Okt  

def okt_text_preprocessing(text_list):
    tokenizer=Okt()  

    stopwords = ['에','을','를','이', '은','는','도','다','라' '있', '하', '것', '들', '그', '되', '수', '이', '보', '않', '없', '나', '주', '아니', '등', '같', '때', '년', '가', '한', '지', '대하', '오', '말', '일', '그렇', '위하']      
  
    token_list = [] 
    word_name = []
    word_cnt=[]
    
    for text in text_list:
     #   text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', '', text)
     #   text = re.sub('[\n+]', '', text)
     #   text = re.sub(r"[0-9]+", ' ', text) 
       # text = re.sub('[을-를-이-가-걸-아]', '', text)

        text = re.sub('[ㅋ.+]', '', text)
        hangul = re.compile('[^ ㄱ-ㅣ가-힣 a-zA-Z]+')
        text = hangul.sub('', text)
        token = tokenizer.morphs(text) #형태소 분석

        token = [t for t in token] 
        token_list.append(token)

        # bow
        word2index={}  
        bow=[]  
        for voca in token:  
                if voca in stopwords:
                  continue
                elif voca not in word2index.keys():  
                #if voca not in word2index.keys():  
                    word2index[voca]=len(word2index)  
        # token을 읽으면서, word2index에 없는 (not in) 단어는 새로 추가하고, 이미 있는 단어는 넘깁니다.   
                    bow.insert(len(word2index)-1,1)
        # BoW 전체에 전부 기본값 1을 넣어줍니다. 단어의 개수는 최소 1개 이상이기 때문입니다.  
                else:
                    index=word2index.get(voca)
        # 재등장하는 단어의 인덱스를 받아옵니다.
                    bow[index]=bow[index]+1
        # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더해줍니다. (단어의 개수를 세는 것입니다.)  
        #print(word2index)

        #word_name = word2index

        word_name.append(list(word2index.keys()))
        word_cnt.append(bow)
#        word_cnt.append(list(word2index.values()))  
        
    return token_list, tokenizer, word_name, word_cnt

df['okt_content'], okt, word_name, word_cnt = okt_text_preprocessing(df['Message'])

In [ ]:
# word_name

In [ ]:
word_name = np.concatenate(word_name).tolist()
word_name

word_cnt = np.concatenate(word_cnt).tolist()
# word_cnt

In [ ]:
word_df = pd.DataFrame({
            'word_name': word_name,
           'word_cnt': word_cnt})
word_df

word_name  word_cnt
0            이장       1.0
1             후       1.0
2             님       4.0
3           최우혁       1.0
4            나영       1.0
...         ...       ...
21875        실습       1.0
21876        해봐       1.0
21877     야하는거지       1.0
21878         녜       1.0
21879         옙       1.0

[21880 rows x 2 columns]

In [ ]:
len(word_df.word_name.unique())

5631

In [ ]:
#len(khaiii_word_df.khaiii_word_name.unique())

In [ ]:
#khaiii_word_df

In [ ]:
# khaiii_word_df = khaiii_word_df.groupby(khaiii_word_df.khaiii_word_name).sum()
#khaiii_word_sort_df= khaiii_word_df.sort_values(by="khaiii_word_cnt", ascending=False)#.groupby("grp").head(3)

#khaiii_word_sort_df.head(20)

In [ ]:
#khaiii_word_sort_df.head(40)

In [ ]:
# word_sort_df.head(60)

In [ ]:
word_df = word_df.groupby(word_df.word_name).sum()
word_sort_df= word_df.sort_values(by="word_cnt", ascending=False)#.groupby("grp").head(3)

word_sort_df.head(60)

word_cnt
word_name          
팀             295.0
이모티콘          263.0
사진            232.0
으로            176.0
동아리           165.0
님             161.0
입니다           147.0
로             137.0
분             135.0
아             129.0
만             127.0
에서            118.0
저             117.0
사람            115.0
의             111.0
안             110.0
해             110.0
하고            109.0
시             106.0
오늘             93.0
명              91.0
생각             91.0
할              89.0
네              87.0
활동             87.0
문제             86.0
거              86.0
잘              86.0
저희             85.0
요              83.0
학기             81.0
고              80.0
못              80.0
관심             79.0
영채             79.0
회의             78.0
하는             77.0
적              77.0
내              77.0
I              74.0
까지             74.0
지원             74.0
진행             73.0
합니다            72.0
좀              71.0
그럼             70.0
스터디            69.0
함께             69.0
우리             68.0
지금             67.0
주희             65.0
된              64.0
확인             63.0
A              63.0
더              62.0
월              62.0
해서             61.0
참여             60.0
중              59.0
링크             59.0

In [ ]:
"""word2index={}  
bow=[]  
for voca in token:  
         if voca not in word2index.keys():  
             word2index[voca]=len(word2index)  
# token을 읽으면서, word2index에 없는 (not in) 단어는 새로 추가하고, 이미 있는 단어는 넘깁니다.   
             bow.insert(len(word2index)-1,1)
# BoW 전체에 전부 기본값 1을 넣어줍니다. 단어의 개수는 최소 1개 이상이기 때문입니다.  
         else:
            index=word2index.get(voca)
# 재등장하는 단어의 인덱스를 받아옵니다.
            bow[index]=bow[index]+1
# 재등장한 단어는 해당하는 인덱스의 위치에 1을 더해줍니다. (단어의 개수를 세는 것입니다.)  
print(word2index)  """

'word2index={}  \nbow=[]  \nfor voca in token:  \n         if voca not in word2index.keys():  \n             word2index[voca]=len(word2index)  \n# token을 읽으면서, word2index에 없는 (not in) 단어는 새로 추가하고, 이미 있는 단어는 넘깁니다.   \n             bow.insert(len(word2index)-1,1)\n# BoW 전체에 전부 기본값 1을 넣어줍니다. 단어의 개수는 최소 1개 이상이기 때문입니다.  \n         else:\n            index=word2index.get(voca)\n# 재등장하는 단어의 인덱스를 받아옵니다.\n            bow[index]=bow[index]+1\n# 재등장한 단어는 해당하는 인덱스의 위치에 1을 더해줍니다. (단어의 개수를 세는 것입니다.)  \nprint(word2index)  '

In [ ]:
df

Date  ...                                        okt_content
0     2020-08-01 21:13:00  ...  [이장, 후, 님, 이, 최우혁, 님, 나영, 채, 님, 과, 이주희, 님, 을, ...
1     2020-08-01 21:13:00  ...                                            [안녕하세요]
2     2020-08-01 21:13:00  ...                                             [이모티콘]
3     2020-08-01 21:16:00  ...  [SAI, 캘린더, 연동, 하기, SAI, 회의, 록, notion, 초대, SAI...
4     2020-08-01 21:21:00  ...          [Notion, google, mail, 로, 초대, 했, 습, 니, 담]
...                   ...  ...                                                ...
4973  2021-05-13 18:06:00  ...                     [데이터, 로, 바꾸는, 코드, 를, 올려놓은, 건데]
4974  2021-05-13 18:06:00  ...                                        [아아, ㅏ, 글쿵]
4975  2021-05-13 18:07:00  ...               [그럼, 각자, 데이터, 변환, 해서, 실습, 해봐, 야하는거지]
4976  2021-05-13 18:50:00  ...                                                [녜]
4977  2021-05-13 19:07:00  ...                                                [옙]

[4978 rows x 4 columns]

### 토픽 모델링
- 텍스트 본문의 숨겨진 의미 구조를 발견

In [ ]:
# khaiii content를 다시 하나의 문장으로 바꾸기

def list_to_str(word_list):
  new_df = []
  for word in word_list:
    new_df.append(' '.join(word))
  return new_df

df['Message_by_okt_content'] = list_to_str(df['okt_content'])
df['Message_by_okt_content']

0                 이장 후 님 이 최우혁 님 나영 채 님 과 이주희 님 을 초대 했습니다
1                                                   안녕하세요
2                                                    이모티콘
3       SAI 캘린더 연동 하기 SAI 회의 록 notion 초대 SAI 회의 록 구글독스...
4                         Notion google mail 로 초대 했 습 니 담
                              ...                        
4973                               데이터 로 바꾸는 코드 를 올려놓은 건데
4974                                              아아 ㅏ 글쿵
4975                          그럼 각자 데이터 변환 해서 실습 해봐 야하는거지
4976                                                    녜
4977                                                    옙
Name: Message_by_okt_content, Length: 4978, dtype: object

In [ ]:
# countVectorizer

from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
print(vector.fit_transform(df['Message_by_okt_content']).toarray()) # 코퍼스로부터 각 단어의 빈도 수를 기록한다.
print(vector.vocabulary_) 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
{'이장': 3698, '최우혁': 4393, '나영': 1047, '이주희': 3702, '초대': 4380, '했습니다': 4980, '안녕하세요': 2956, '이모티콘': 3666, 'sai': 272, '캘린더': 4441, '연동': 3284, '하기': 4677, '회의': 5063, 'notion': 233, '구글독스': 766, '내용': 1133, '으로': 3575, '옮기기': 3461, 'google': 71, 'mail': 215, '영채': 3316, '다음주': 1303, '화요일': 5042, '간단히': 475, '정리': 4036, '생각': 2580, '이지만': 3705, '통해': 4538, '역할': 3281, '분담': 2422, '해서': 4905, '작성': 3920, '거나': 584, '해보아야': 4885, '있다면': 3830, '직접': 4269, '들어가서': 1603, '업로드': 3184, '주시': 4180, '됩니다': 1538, '저희': 3993, '동아리': 1450, '아니라': 2886, '나중': 1069, '에도': 3245, '많이': 1831, '사용': 2530, '하실': 4755, '니까': 1276, '하는거': 4691, '이참': 3708, '익혀': 3722, '두세요': 1546, '사진': 2538, '일정': 3763, '관련': 725, '우선': 3511, '괜찮나': 735, '실험': 2794, '해볼': 4889, '있는': 3819, '공유': 714, '설정': 2625, '구글': 765, '컴퓨터': 4461, '에서': 3249, '아마': 2916, '메일': 1935, '받으면': 2157, '구독': 770, '있을거에요': 3

In [ ]:
#LDA 는 Count기반의 Vectorizer만 적용합니다.  

stopwords = ['에','을','를','이', '은','는','도','다','라' '있', '하', '것', '들', '그', '되', '수', '이', '보', '않', '없', '나', '주', '아니', '등', '같', '때', '년', '가', '한', '지', '대하', '오', '말', '일', '그렇', '위하']      

count_vect = CountVectorizer(max_df=0.95, max_features=100, min_df=2, stop_words=stopwords, ngram_range=(1,6))
feat_vect = count_vect.fit_transform(df['Message_by_okt_content'])
print('CountVectorizer Shape:', feat_vect.shape)

CountVectorizer Shape: (4978, 100)


In [ ]:
from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(n_components=4, random_state=0)
lda.fit(feat_vect)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=4, n_jobs=None,
                          perp_tol=0.1, random_state=0, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [ ]:
print(lda.components_.shape)
lda.components_

(4, 100)


array([[2.32667264e+01, 2.54728926e-01, 3.82177038e+01, 1.56658825e+01,
        2.53508300e-01, 3.52466640e+01, 2.52067111e-01, 3.99570878e+00,
        2.53580588e-01, 2.50002253e-01, 2.54885249e-01, 2.65284275e-01,
        2.54411612e-01, 2.57066675e-01, 7.42294372e+01, 2.57003784e-01,
        4.02466119e+01, 4.92364498e+01, 2.55779558e-01, 2.54592239e-01,
        2.85292293e+01, 2.56384543e+01, 2.52966233e-01, 2.53712445e-01,
        2.77996681e-01, 2.51124874e-01, 1.59384960e+01, 2.51267694e-01,
        2.51267694e-01, 2.50989896e-01, 2.50034045e-01, 2.57803942e-01,
        2.60392082e-01, 1.01957543e+01, 7.37313795e+00, 2.50246507e-01,
        2.54408639e-01, 2.50417729e-01, 2.50039697e-01, 2.50034045e-01,
        2.50034045e-01, 2.53350128e-01, 2.51476792e-01, 4.91461998e+01,
        2.52694563e-01, 1.12276663e+01, 2.51037813e-01, 2.54072931e-01,
        2.53795790e-01, 1.08180746e+00, 2.35590289e+01, 7.92419271e+01,
        9.32454687e+01, 3.32489946e+01, 2.50701142e-01, 6.290996

In [ ]:

def display_topics(model, feature_names, no_top_words):
    for topic_index, topic in enumerate(model.components_):
        print('Topic #',topic_index)

        # components_ array에서 가장 값이 큰 순으로 정렬했을 때, 그 값의 array index를 반환. 
        topic_word_indexes = topic.argsort()[::-1]
        top_indexes=topic_word_indexes[:no_top_words]
        
        # top_indexes대상인 index별로 feature_names에 해당하는 word feature 추출 후 join으로 concat
        feature_concat = ' '.join([feature_names[i] for i in top_indexes])                
        print(feature_concat)

# CountVectorizer객체내의 전체 word들의 명칭을 get_features_names( )를 통해 추출
feature_names = count_vect.get_feature_names()

# Topic별 가장 연관도가 높은 word를 15개만 추출
display_topics(lda, feature_names, 30)

Topic # 0
오늘 영채 까지 우리 너무 시간 해서 저희 내일 우혁 조금 ㅎㅎ 확인 혹시 고생 오케이 이랑 다시 다음 연락 sai 회의 링크 ㅠㅠ 참여 안녕하세요 초대 발표 일단 부터
Topic # 1
사진 으로 그럼 주희 누나 한번 생각 그냥 주희 누나 오키 조사 하면 입니다 이렇게 근데 어떻게 하는 아직 해도 기간 확인 합니다 공지 진행 내용 인원 우선 주세요 있습니다 sai
Topic # 2
문제 입니다 지금 회의 이번 메시지 사람 삭제 메시지 입니다 삭제 메시지 삭제 메시지 입니다 다음주 에서 어디 정도 에는 링크 작성 운영 다른 초대 저희 내용 한테 진행 안녕하세요 이렇게 어떻게 됩니다 sai
Topic # 3
이모티콘 동아리 하고 활동 으로 학기 관심 에서 지원 스터디 함께 사람 합니다 지능 진행 하는 인공 인공 지능 러닝 season ㅠㅠ 참여 발표 분야 공부 생각 입니다 하지 저희 관심 분야


- Tfidf vectorizer 사용

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

stopwords = ['에','을','를','이', '은','는','도','다','라' '있', '하', '것', '들', '그', '되', '수', '이', '보', '않', '없', '나', '주', '아니', '등', '같', '때', '년', '가', '한', '지', '대하', '오', '말', '일', '그렇', '위하']      


vectorizer = TfidfVectorizer(stop_words=stopwords, max_features= 1000) # 상위 1,000개의 단어를 보존 
X = vectorizer.fit_transform(df['Message_by_okt_content'])
X.shape # TF-IDF 행렬의 크기 확인

(4978, 1000)

In [ ]:
lda_model=LatentDirichletAllocation(n_components=4,learning_method='online',random_state=777,max_iter=1)
lda_top=lda_model.fit_transform(X)

In [ ]:
lda_top

array([[0.07785792, 0.7620832 , 0.08252521, 0.07753367],
       [0.12504845, 0.12506084, 0.62471494, 0.12517578],
       [0.1250008 , 0.62499478, 0.12500369, 0.12500073],
       ...,
       [0.23716812, 0.07826001, 0.60097311, 0.08359877],
       [0.25      , 0.25      , 0.25      , 0.25      ],
       [0.25      , 0.25      , 0.25      , 0.25      ]])

In [ ]:
terms = vectorizer.get_feature_names() # 단어 집합. 1,000개의 단어가 저장됨.

def get_topics(components, feature_names, n=10):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n - 1:-1]])
get_topics(lda_model.components_,terms)

Topic 1: [('문제', 63.88), ('사람', 43.1), ('오늘', 42.73), ('그럼', 39.99), ('너무', 32.0), ('그냥', 26.95), ('한번', 26.89), ('ㅇㅅㅇ', 24.21), ('회의', 23.01), ('고생', 22.21)]
Topic 2: [('이모티콘', 208.38), ('ㅠㅠ', 35.58), ('누나', 33.24), ('확인', 33.13), ('오키', 31.1), ('주희', 25.93), ('이번', 23.62), ('같은데', 23.39), ('다시', 22.73), ('까지', 21.54)]
Topic 3: [('오케이', 39.7), ('우리', 36.75), ('입니다', 34.41), ('메시지', 33.37), ('삭제', 31.51), ('하고', 24.35), ('여기', 22.99), ('근데', 22.85), ('운영', 19.92), ('맞아', 19.63)]
Topic 4: [('사진', 247.32), ('영채', 41.99), ('지금', 40.87), ('웅웅', 36.94), ('생각', 36.84), ('으로', 34.46), ('우혁', 27.13), ('진짜', 22.41), ('이렇게', 22.37), ('링크', 19.94)]
